name: eco
version: ${projectVersion}
main: com.willfp.eco.internal.spigot.EcoImpl
api-version: 1.21.4
authors: [ Auxilor ]
website: willfp.com
load: STARTUP

# Fixes some plugins breaking load order
loadbefore:
  - Spartan
  - CustomCrafting
  - Lands
  - EconomyShopGUI
  - EconomyShopGUI-Premium
  - CMI
  - DeluxeCombat
  - ShopGUIPlus
  - DeluxeMenus
  - Nexo
softdepend:
  # AntiGrief
  - HuskClaims
  - HuskTowns
  - WorldGuard
  - GriefPrevention
  - Towny
  - FactionsUUID
  - Kingdoms
  - CombatLogX
  - BentoBox
  - IridiumSkyblock
  - SuperiorSkyblock2
  - FabledSkyBlock
  - PvPManager
  - RPGHorses
  - TogglePvp
  # Custom Items
  - ItemBridge
  - ItemsAdder
  - Oraxen
  - Nexo
  - HeadDatabase
  - Scyther
  # AntiCheat
  - NoCheatPlus
  - AAC
  - Matrix
  - Vulcan
  - Alice
  # Holograms
  - FancyHolograms
  - HolographicDisplays
  - DecentHolograms
  - GHolo
  # Shop/Economy
  - zShop
  - DeluxeSellwands
  - Vault
  - RoyaleEconomy
  - UltraEconomy
  - PlayerPoints
  # Other/Misc
  - Terra
  - ProtocolLib
  - PlaceholderAPI
  - mcMMO
  - Multiverse-Inventories
  - Essentials
  - MythicMobs
  - ModelEngine
  - DeluxeMenus
  - Denizen